### ISSUE TITLE
Running example code fails

### ISSUE THREAD

**Issue by BasKiers** [bluetoother/ble-shepherd#7]
Hi, I am trying to get your module to work since I need exactly this for one of my projects. The problem is that I get exceptions with everything I tried. The exceptions I get are also thrown when running the example code. I am running node 4.4.6 with npm 3.10.5.

```
node node_modules/ble-shepherd/examples/sensorTagApp.js
>> Central has completed initialization
>> Loading devices from database.
>> Asynchrnously connect devices in database.
>> Starting bleApp.
1efd028b107847ff82242c2864ef0060
4371c199495d46f593f68b2b017f920d
4371c199495d46f593f68b2b017f920d
adc3e3141ca049eca8730c1e6f6aea80
adc3e3141ca049eca8730c1e6f6aea80
8c4f5a3b28534c219099ded02f5d21e0
8c4f5a3b28534c219099ded02f5d21e0
/Users/xxxx/xxxx/temp/bluetooth/node_modules/ble-shepherd/lib/csr8510/peripheral.js:21
    this.connHdl = peripheral._noble._bindings._handles[peripheral.id];
                                                       ^

TypeError: Cannot read property '1efd028b107847ff82242c2864ef0060' of undefined
    at new Peripheral (/Users/xxxx/xxxx/temp/bluetooth/node_modules/ble-shepherd/lib/csr8510/peripheral.js:21:56)
    at peripheralWrapper (/Users/xxxx/xxxx/temp/bluetooth/node_modules/ble-shepherd/lib/csr8510/ble-shepherd.js:557:25)
    at /Users/xxxx/xxxx/temp/bluetooth/node_modules/ble-shepherd/lib/csr8510/ble-shepherd.js:482:37
    at Peripheral.<anonymous> (/Users/xxxx/xxxx/temp/bluetooth/node_modules/noble/lib/peripheral.js:39:7)
    at Peripheral.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Peripheral.emit (events.js:169:7)
    at Noble.onConnect (/Users/xxxx/xxxx/temp/bluetooth/node_modules/noble/lib/noble.js:190:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
```

And

```
node node_modules/ble-shepherd/examples/sensorTagApp.js
>> Central has completed initialization
>> Loading devices from database.
>> Asynchrnously connect devices in database.
>> Starting bleApp.
853ea8da881f47eaa61431d4649ba227
853ea8da881f47eaa61431d4649ba227
b543e27088f842ae8f8dd8e2c4ed3160
4371c199495d46f593f68b2b017f920d
1efd028b107847ff82242c2864ef0060
ae748e16d0414c90ba0dd8cc069f7c32
4371c199495d46f593f68b2b017f920d
1efd028b107847ff82242c2864ef0060
4371c199495d46f593f68b2b017f920d
853ea8da881f47eaa61431d4649ba227
/Users/xxxx/xxxx/temp/bluetooth/node_modules/noble/lib/noble.js:182
  this._bindings.connectCalcel(peripheralUuid);
                 ^

TypeError: this._bindings.connectCalcel is not a function
    at Noble.connectCancel (/Users/xxxx/xxxx/temp/bluetooth/node_modules/noble/lib/noble.js:182:18)
    at Peripheral.connectCancel (/Users/xxxx/xxxx/temp/bluetooth/node_modules/noble/lib/peripheral.js:56:15)
    at null._onTimeout (/Users/xxxx/xxxx/temp/bluetooth/node_modules/ble-shepherd/lib/csr8510/ble-shepherd.js:475:28)
    at Timer.listOnTimeout (timers.js:92:15)
```

The devices in question that throw the errors are:

```
node examples/peripheral-explorer.js 1efd028b107847ff82242c2864ef0060
peripheral with ID 1efd028b107847ff82242c2864ef0060 found
  Local Name        = Apple TV
  Manufacturer Data = 4c000906022bc0a80172
  Service Data      = 
  Service UUIDs     = 

services and characteristics:
d0611e78bbb44591a5f8487910ae4366
  8667556c9a374c9184ed54ee27d90049
    properties  write, notify, extendedProperties
```

And

```
node examples/peripheral-explorer.js 8c4f5a3b28534c219099ded02f5d21e0
peripheral with ID 8c4f5a3b28534c219099ded02f5d21e0 found
  Local Name        = Eve
  Service Data      = [object Object]
  Service UUIDs     = fed4

services and characteristics:
fed4
  000000510000100080000026bb765291
    properties  read
    value       32 | '2'
  0000004f0000100080000026bb765291
    properties  read
    value       01 | ''
  0000004c0000100080000026bb765291
    properties  read, write
    value        | ''
  0000004e0000100080000026bb765291
    properties  read, write
    value        | ''
  000000500000100080000026bb765291
    properties  read, write
fed3
  000000510000100080000026bb765291
    properties  read
    value       31 | '1'
  000000230000100080000026bb765291
    properties  read
  000000200000100080000026bb765291
    properties  read
  000000210000100080000026bb765291
    properties  read
  000000300000100080000026bb765291
    properties  read
  000000140000100080000026bb765291
    properties  write
  000000520000100080000026bb765291
    properties  read
fed1
  000000510000100080000026bb765291
    properties  read
    value       33 | '3'
  000000230000100080000026bb765291
    properties  read
  e863f11e079e48ff8f279c2605a29f52
    properties  read, write
  000000110000100080000026bb765291
    properties  read
  000000350000100080000026bb765291
    properties  read, write
  0000000f0000100080000026bb765291
    properties  read
  000000330000100080000026bb765291
    properties  read, write
  000000360000100080000026bb765291
    properties  read, write
  e863f12e079e48ff8f279c2605a29f52
    properties  read
  e863f12c079e48ff8f279c2605a29f52
    properties  read, write
000000960000100080000026bb765291
  000000510000100080000026bb765291
    properties  read
    value       37 | '7'
  000000230000100080000026bb765291
    properties  read
  000000680000100080000026bb765291
    properties  read
  0000008f0000100080000026bb765291
    properties  read
  000000790000100080000026bb765291
    properties  read
e863f007079e48ff8f279c2605a29f52
  000000510000100080000026bb765291
    properties  read
    value       38 | '8'
  e863f112079e48ff8f279c2605a29f52
    properties  read, write
  e863f11c079e48ff8f279c2605a29f52
    properties  write
  e863f121079e48ff8f279c2605a29f52
    properties  write
  e863f116079e48ff8f279c2605a29f52
    properties  read
  e863f117079e48ff8f279c2605a29f52
    properties  read
  e863f11d079e48ff8f279c2605a29f52
    properties  read, write
```

**Comment by hedywings** [comment]
Hi, BasKiers,

Thanks for your feedback. It seems to be caused by the platform issue, are you running on OS X? At this moment, ble-shepherd with [noble](https://github.com/sandeepmistry/noble) submodule only supports Linux and Windows platforms, some error may occur if you are running it on other platforms. 

Or you can try to use TI CC2540 Dongle, there would be no issue on different platforms.
