### ISSUE TITLE
error about Parameter length incorrect q module 

### ISSUE THREAD

**Issue by amigomcu** [bluetoother/ble-shepherd#9]
hi all,
i try it with example,it get a error about Parameter length incorrect q module .

λ node --version
v6.10.1

λ npm --version
3.10.10

c:\temp\node_modules\q\q.js:155                                
                throw e;                                       
                ^                                              
                                                               
Error: Parameter length incorrect.                             
    at ArgObj.getHciEvtPacket (c:\temp\node_modules\ble-shepher
d\node_modules\cc-bnp\lib\hci\hciEvtDiscriminator.js:77:25)    
    at BleHci.appLevelHandler (c:\temp\node_modules\ble-shepher
d\node_modules\cc-bnp\lib\hci\bleHci.js:271:12)                
    at emitOne (events.js:96:13)                               
    at BleHci.emit (events.js:188:7)                           
    at BleRawUint.onEventHdlr (c:\temp\node_modules\ble-shepher
d\node_modules\cc-bnp\lib\hci\bleHci.js:258:12)                
    at emitOne (events.js:96:13)                               
    at BleRawUint.emit (events.js:188:7)                       
    at Dissolve.spDataHandler (c:\temp\node_modules\ble-shepher
d\node_modules\cc-bnp\lib\hci\bleRawUnit.js:175:20)            
    at emitOne (events.js:96:13)                               
    at Dissolve.emit (events.js:188:7)                         
    at Dissolve.<anonymous> (c:\temp\node_modules\dissolve-chun
ks\index.js:73:29)                                             
    at emitNone (events.js:86:13)                              
    at Dissolve.emit (events.js:185:7)                         
    at emitReadable_ (c:\temp\node_modules\readable-stream\lib\
_stream_readable.js:456:10)                                    
    at emitReadable (c:\temp\node_modules\readable-stream\lib\_
stream_readable.js:450:7)                                      
    at readableAddChunk (c:\temp\node_modules\readable-stream\l
ib\_stream_readable.js:206:11)

**Comment by hedywings** [comment]
Hi @amigomcu, the error is caused by cc-bnp, I have fixed the problem and updated the dependency, please try again, thank you!

**Comment by amigomcu** [comment]
hi hedywings,
excause me , 
this is my Environment Setup issue.

I will be grateful for any help you can provide.
